#!/bin/bash
# SPDX-License-Identifier: zlib-acknowledgement 

simulation_file=$(ls -t build/*-simulator.elf | head -n1)

# -display none
qemu-system-arm -S -machine netduinoplus2 -g 1234 "${simulation_file}"
