#!/bin/bash
# SPDX-License-Identifier: zlib-acknowledgement 

# ./configure --help 
# ./configure --target-list="arm-softmmu"
# make -j$(getconf _NPROCESSORS_ONLN)

simulation_file=$(ls -t build/*-simulator.elf | head -n1)

# -display none
qemu-system-arm -S -machine netduinoplus2 -g 1234 "${simulation_file}"
