#!/bin/bash

# IMPORTANT(Ryan): We cannot exit on error otherwise when tests fail, build will exit prematurely
# set -oue pipefail
set -u

build_start_time=$(date +%s.%N)

if [[ "$1" != "app" && "$1" != "tests" ]]; then
  printf "Usage: ./build <app|tests>\n" >&2
  exit 1
fi

BUILD_TYPE="$1"

error() {
  printf "Error: %s\n" "$1" >&2
  exit 1
}

push_dir() {
  command pushd "$@" > /dev/null
}

pop_dir() {
  command popd "$@" > /dev/null
}

# IMPORTANT(Ryan): Want to include bytes for initialisation values for static variables in .data section that will occupy flash
readonly max_flash_size=$(( 2048 << 10 ))
print_flash_usage() {
  raw_size_output=$(arm-none-eabi-size $1)
  
  text_section_size=$(echo $raw_size_output | cut -d ' ' -f 7)
  data_section_size=$(echo $raw_size_output | cut -d ' ' -f 8)
  
  flash_size=$(( $text_section_size + $data_section_size ))
  # NOTE(Ryan): Rearrange multiplication due to implicit truncation
  flash_usage=$(( 100 * $flash_size / $max_flash_size )) 

  printf "Flash usage: %d / %d (%d%%)\n" $flash_size $max_flash_size $flash_usage
}

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  build_os="linux"
else
  error "Currently only support linux as build machine"
fi

# NOTE(Ryan): This file is ignored by source control to allow tweaking of build params without affecting history
source "private/build-params"
param_compiler=${param_compiler:-"arm-none-eabi-gcc"}
param_mode=${param_mode:-"debug"}
param_arch=${param_arch:-"arm"}
param_verbose=${param_verbose:-"0"}
param_mcu=${param_mcu:-"stm32f429zitx"}

mkdir -p build run

target_compiler_flags=()
target_linker_flags=()
test_compiler_flags=()
test_linker_flags=()
# TODO(Ryan): Simulator
# simulator_compiler_flags=()
# simulator_linker_flags=()

if [[ "$param_arch" == "arm" && "$param_compiler" == "arm-none-eabi-gcc" && "$param_mcu" == "stm32f429zitx" && "$build_os" == "linux" ]]; then

  # TODO(Ryan): Derive version string from a meaningful source
  # TODO(Ryan): Allow for spaces
  printf -v build_date '\"%s\"' $(date '+%c(%:z%Z)' | tr ' ' '-')
  printf -v build_version '\"0.0.1\"'
  printf -v ram_size '%d' $(( 192 << 10 ))
  target_compiler_flags+=( "-DBUILD_VERSION_STR=$build_version" "-DBUILD_DATE_STR=$build_date" "-DRAM_SIZE_INT=$ram_size" )

  # IMPORTANT(Ryan): Unfortunately new errors aren't added to -Wall and -Wextra for backwards compatibility

  # NOTE(Ryan): Enable various warnings largely related to implicit signed, alignment, casting, promotion issues
  target_compiler_flags+=( "-Wall" "-Wextra" "-Wshadow" "-Wconversion" "-Wdouble-promotion" "-Wformat=2" "-pedantic" )
  target_compiler_flags+=( "-Wundef" "-Wshadow" "-Wpadded" "-fno-common" )
  target_compiler_flags+=( "-Wfloat-equal" "-Wlogical-op" "-Wredundant-decls" "-Wstrict-overflow=2" "-Warray-bounds=2" )
  target_compiler_flags+=( "-Wwrite-strings" "-Wpointer-arith" "-Wformat-truncation" "-Wmissing-include-dirs" )
  target_compiler_flags+=( "-Wcast-align" "-Wswitch-enum" "-Wsign-conversion" "-Wdisabled-optimization" )
  target_compiler_flags+=( "-Winline" "-Wmissing-declarations" "-Wdouble-promotion" "-Wshadow" "-Wtrampolines" )
  target_compiler_flags+=( "-Wvector-operation-performance" "-Wnull-dereference" "-Winvalid-pch" )
  target_compiler_flags+=( "-Wduplicated-cond" "-Wshift-overflow=2" "-Wcast-align=strict" )

  # NOTE(Ryan): Display the specific warning flag so we can ignore it if needed
  target_compiler_flags+=( "-fdiagnostics-show-option" )

  # NOTE(Ryan): Ignored warnings
  target_compiler_flags+=( "-Wno-unknown-pragmas" "-Wno-missing-field-initializers" "-Wno-cast-align" "-Wno-comment" "-Wno-missing-declarations" )

  target_compiler_flags+=( "-ffunction-sections" "-fdata-sections" )

  target_compiler_flags+=( "-I code" "-I code/base" )

  target_linker_flags+=( "-Wl,--gc-sections" "-lc" "-lm" )

  # NOTE(Ryan): BSP includes
  hal_path="stm32f429zitx-bsp/Drivers/STM32F4xx_HAL_Driver"
  target_compiler_flags+=( "-DUSE_HAL_DRIVER" "-DSTM32F429xx" ) 
  target_compiler_flags+=( "-isystem ${hal_path}/Inc" "-isystem ${hal_path}/Inc/Legacy" )
  target_compiler_flags+=( "-isystem stm32f429zitx-bsp/Drivers/CMSIS/Device/ST/STM32F4xx/Include" )
  target_compiler_flags+=( "-isystem stm32f429zitx-bsp/Drivers/CMSIS/Include" )
  target_compiler_flags+=( "-isystem ${hal_path}/Src" )

  # IMPORTANT(Ryan): Have to macro-out inline assembly found in CMSIS files that only detect gcc, not arm-gcc
  test_compiler_flags=("${target_compiler_flags[@]}")
  test_compiler_flags+=( "-Wno-padded" "-Wno-conversion" "-I tests" "-DTEST_BUILD" )
  test_linker_flags=("${target_linker_flags[@]}")
  test_linker_flags+=( "-lcmocka" "-Wl,--warn-unresolved-symbols" )

  # TODO(Ryan): Simulator
  # simulator_compiler_flags=$target_compiler_flags
  # simulator_compiler_flags+=$( "-mfloat-abi=soft" "--specs=rdimon.specs" )
  # simulator_linker_flags+=$( "-lrdimon" )

  target_compiler_flags+=( "-mcpu=cortex-m4" "-mthumb" )
  target_compiler_flags+=( "-mfloat-abi=hard" "-mfpu=fpv4-sp-d16" "--specs=nano.specs" )
  target_linker_flags+=( "-lnosys" "-Wl,-Map=build/${param_mcu}-target-${param_mode}.map,--cref" )

  # NOTE(Ryan): BSP files
  target_compiler_flags+=( "code/startup_stm32f429zitx.s" )
  target_linker_flags+=( "-Tcode/STM32F429ZITX_FLASH.ld" )

  if [[ "$param_mode" == "debug" ]]; then
    common_debug_flags=( "-Wno-unused-function" "-Wno-unused-variable"  "-Wno-unused-but-set-variable" "-Wno-unused-parameter" "-Wno-unused-result" )
    common_debug_flags+=( "-DDEBUG_BUILD" "-g3" "-gdwarf-2" "-O0" )
    target_compiler_flags+=( "${common_debug_flags[@]}" )
    test_compiler_flags+=( "${common_debug_flags[@]}" "--coverage" )

  elif [[ "$param_mode" == "release" ]]; then
    common_release_flags=( "-DRELEASE_BUILD" "-Os" "-ffast-math" "-fipa-pta" )
    target_compiler_flags+=( "${common_release_flags[@]}" ) 
    test_compiler_flags+=( "${common_release_flags[@]}" ) 

  else
    error "Currently only support debug and release builds"
  fi

  # TODO(Ryan): Don't run coverage if in a release build
  if [[ "$BUILD_TYPE" == "tests" ]]; then

    # TODO(Ryan): Mock setup
    # determine container-id from running container and $(docker container ls)
    # sudo -i

    # has to be to /tmp/ for snap reasons ...
    # will go inside of /tmp/snap-private-tmp/...
    # sudo docker cp container-id:/path/filename.txt /tmp/

    # chmod -R 777 file
    # chown -R ryan:ryan file
    # mv file /home/ryan/prog/personal/learn/unit2

    # TODO(Ryan): Incorporate application code into compile
    # NOTE(Ryan): This generates .gcno files
    
    test_linker_flags+=( "-Wl,--wrap=HAL_Init" "-Wl,--wrap=SystemClock_Config" )

    gcc ${test_compiler_flags[*]} \
      tests/${param_mcu}-tests.c -o build/${param_mcu}-tests-${param_mode} \
      ${test_linker_flags[*]}

    # NOTE(Ryan): gcov complains if overriding existing .gcda files
    find -name '*.gcda' -exec rm -f {} +

    # NOTE(Ryan): This generates .gcna files
    push_dir run
      test_output=$(../build/${param_mcu}-tests-${param_mode})
      test_success=$?
    pop_dir

    if [[ $test_success = 0 ]]; then
      echo "$test_output"

      # TODO(Ryan): lcov for graphical information 
      # NOTE(Ryan): This generates a .gcov file
      # IMPORTANT(Ryan): This has to be the same version as gcc
      gcov-10 -b -o . tests/${param_mcu}-tests.c >/dev/null

      gcovr -e ".*\.h"

      find . -name '*.gcov' -or -name '*.gcda' -or -name '*.gcno' -exec rm -f {} +
    else
      echo "$test_output"
    fi
  else
    arm-none-eabi-gcc ${target_compiler_flags[*]} \
      code/${param_mcu}-main.c -o build/${param_mcu}-target-${param_mode}.elf \
      ${target_linker_flags[*]}

    arm-none-eabi-objcopy -O binary build/${param_mcu}-target-${param_mode}.elf build/${param_mcu}-target-${param_mode}.bin
    arm-none-eabi-objcopy -O ihex build/${param_mcu}-target-${param_mode}.elf build/${param_mcu}-target-${param_mode}.hex
  fi

  # TODO(Ryan): Simulator
  # arm-none-eabi-gcc ${compiler_flags[*]} code/linux-main.cpp -o build/stm32f2323-simulator-debug.elf ${linker_flags[*]}

else
  error "Currently only support arm arm-none-eabi-gcc stm32f429zitx on linux"
fi

print_flash_usage build/${param_mcu}-target-${param_mode}.elf

build_end_time=$(date +%s.%N)
build_time=$( echo "($build_end_time - $build_start_time)" | bc -l )

if [[ "$BUILD_TYPE" == "app" ]]; then 
  printf "Build Time: %.4fs\n" "$build_time" 
  printf "%.4f\n" "$build_time" >> misc/build-time.metric
else
  printf "Build and Test Time: %.4fs\n" "$build_time" 
fi
