#!/bin/bash

docs_path="$HOME/Desktop/docs"

stm32f429zitx_docs=()
stm32f429zitx_docs+=( "$docs_path/arm/cortex-m/cortex-m4/armv7m_arm.pdf" )  
stm32f429zitx_docs+=( "$docs_path/arm/cortex-m/cortex-m4/cortex-m4.pdf" )  
stm32f429zitx_docs+=( "$docs_path/arm/cortex-m/cortex-m4/nucleo-f429zi/board-sch.pdf" )  
stm32f429zitx_docs+=( "$docs_path/arm/cortex-m/cortex-m4/nucleo-f429zi/l-pinout.png" )  
stm32f429zitx_docs+=( "$docs_path/arm/cortex-m/cortex-m4/nucleo-f429zi/r-pinout.png" )  
stm32f429zitx_docs+=( "$docs_path/arm/cortex-m/cortex-m4/nucleo-f429zi/board-um.pdf" )  
stm32f429zitx_docs+=( "$docs_path/arm/cortex-m/cortex-m4/nucleo-f429zi/mcu-datasheet.pdf" )  
stm32f429zitx_docs+=( "$docs_path/arm/cortex-m/cortex-m4/nucleo-f429zi/mcu-rm.pdf" )  

okular ${stm32f429zitx_docs[*]}
